import type { PortalTranslations } from "../translations/portal";
import type { OrdersDocumentLabels, ReceiptDocumentLabels, ReportsDocumentLabels } from "./types";

export function buildReportsDocumentLabels(
  t: PortalTranslations,
): ReportsDocumentLabels {
  const pdf = t.pdfDocuments;
  const r = t.reports;
  const dash = t.labels.dash;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.reportsTitle,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    executiveSummary: pdf.executiveSummary,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    totals: pdf.totals,
    hour: pdf.hour,
    colRevenue: r.colRevenue,
    colOrders: r.colOrders,
    segment: pdf.segment,
    noData: pdf.noData,
    kpiRevenue: r.kpiRevenue,
    kpiOrders: r.kpiOrders,
    kpiReceipts: r.kpiReceipts,
    kpiRefunds: r.kpiRefunds,
    kpiAverageOrder: r.kpiAvgOrder,
    kpiVat: r.kpiVat,
    paymentMethods: r.paymentMethodsTitle,
    paymentCash: r.paymentCash,
    paymentCard: r.paymentCard,
    paymentVoucher: r.paymentVoucher,
    paymentOther: r.paymentOther,
    topProducts: r.topProductsTitle,
    colProduct: r.colProduct,
    colQuantity: r.colQuantity,
    colCategory: r.colCategory,
    topEmployees: r.topEmployeesTitle,
    colEmployee: r.colEmployee,
    colAvgOrder: r.colAvgOrder,
    topEmployeesEmpty: r.topEmployeesEmpty,
    taxes: r.taxesTitle,
    taxNetRevenue: r.taxNetRevenue,
    taxVat: r.taxVat,
    taxGrossRevenue: r.taxGrossRevenue,
    taxFiscalReceipts: r.taxFiscalReceipts,
    businessTrends: r.trendsTitle,
    trendBestDay: r.trendBestDay,
    trendBestHour: r.trendBestHour,
    trendLargestReceipt: r.trendLargestReceipt,
    trendTopPayment: r.trendTopPayment,
    trendTopProduct: r.trendTopProduct,
    salesByHour: r.hourlySalesTitle,
    revenueSection: r.revenueChartTitle,
    dash,
  };
}

export function buildOrdersDocumentLabels(
  t: PortalTranslations,
): OrdersDocumentLabels {
  const pdf = t.pdfDocuments;
  const o = t.orders;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.ordersTitle,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    executiveSummary: pdf.executiveSummary,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    totals: pdf.totals,
    hour: pdf.hour,
    colRevenue: o.colAmount,
    colOrders: o.kpiOrders,
    segment: pdf.segment,
    noData: pdf.noData,
    summary: o.paymentSummaryTitle,
    kpiOrders: o.kpiOrders,
    kpiReceipts: o.kpiReceipts,
    kpiRefunds: o.kpiRefunds,
    paymentSummary: o.paymentSummaryTitle,
    paymentCash: o.paymentCash,
    paymentCard: o.paymentCard,
    paymentVoucher: o.paymentVoucher,
    paymentOther: o.paymentOther,
    allOrders: pdf.allOrders,
    allReceipts: pdf.allReceipts,
    colTime: o.colTime,
    colOrderNumber: o.colOrderNumber,
    colStatus: o.colStatus,
    colPayment: o.colPayment,
    colAmount: o.colAmount,
    colCashier: o.colCashier,
    colDevice: o.colDevice,
    colReceipt: o.colReceipt,
    colCustomer: o.colCustomer,
    colFiscal: o.colFiscal,
    ordersEmpty: o.ordersEmpty,
    receiptsEmpty: o.receiptsEmpty,
    dash: t.labels.dash,
  };
}

export function buildReceiptDocumentLabels(
  t: PortalTranslations,
): ReceiptDocumentLabels {
  const pdf = t.pdfDocuments;
  const o = t.orders;
  const dash = t.labels.dash;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.receiptTitle,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    executiveSummary: pdf.executiveSummary,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    totals: pdf.totals,
    hour: pdf.hour,
    colRevenue: o.colAmount,
    colOrders: o.kpiOrders,
    segment: pdf.segment,
    noData: pdf.noData,
    receiptDetails: o.receiptDetailTitle,
    fiscalPendingNote: o.receiptFiscalPending,
    itemsTitle: o.receiptItemsTitle,
    itemsEmpty: o.receiptItemsEmpty,
    colProduct: o.colProduct,
    colQuantity: o.colQuantity,
    colUnitPrice: o.colUnitPrice,
    colLineTotal: o.colLineTotal,
    colReceipt: o.colReceipt,
    colTime: o.colTime,
    colCustomer: o.colCustomer,
    colPayment: o.colPayment,
    colFiscal: o.colFiscal,
    colAmount: o.colAmount,
    colDevice: o.colDevice,
    paymentCash: o.paymentCash,
    paymentCard: o.paymentCard,
    paymentVoucher: o.paymentVoucher,
    paymentOther: o.paymentOther,
    dash,
  };
}
