import type { PortalTranslations } from "../translations/portal";
import type { OrderDetailDocumentLabels } from "./buildOrderDetailPdfModel";
import type { ReceiptDetailDocumentLabels } from "./buildReceiptDetailPdfModel";
import type { ReceiptsListDocumentLabels } from "./buildReceiptsListPdfModel";
import type {
  OrdersDocumentLabels,
  ReceiptDocumentLabels,
  ReportsDocumentLabels,
} from "./types";

export function buildReportsDocumentLabels(
  t: PortalTranslations,
): ReportsDocumentLabels {
  const pdf = t.pdfDocuments;
  const r = t.reports;
  const o = t.orders;
  const dash = t.labels.dash;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.reportsTitle,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    executiveSummary: pdf.executiveSummary,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    totals: pdf.totals,
    hour: pdf.hour,
    colRevenue: r.colRevenue,
    colOrders: r.colOrders,
    segment: pdf.segment,
    noData: pdf.noData,
    kpiRevenue: r.kpiRevenue,
    kpiOrders: r.kpiOrders,
    kpiReceipts: r.kpiReceipts,
    kpiRefunds: r.kpiRefunds,
    kpiAverageOrder: r.kpiAvgOrder,
    kpiVat: r.kpiVat,
    revenueBreakdownTitle: pdf.revenueSummary,
    ordersBreakdownTitle: pdf.ordersSummary,
    kpiPosRevenue: o.kpiPosRevenue,
    kpiOnlineRevenue: o.kpiOnlineRevenue,
    kpiTotalRevenue: o.kpiTotalRevenue,
    kpiAllOrders: o.kpiAllOrders,
    kpiPosOrders: o.kpiPosOrders,
    kpiOnlineOrders: o.kpiOnlineOrders,
    paymentMethods: r.paymentMethodsTitle,
    paymentPosTitle: o.paymentSummaryTitle,
    paymentOnlineTitle: o.onlinePaymentSummaryTitle,
    paymentScopeNote: r.taxesPosOnlyNote,
    paymentCash: o.paymentCash,
    paymentCard: o.paymentCard,
    paymentVoucher: o.paymentVoucher,
    paymentOther: o.paymentOther,
    onlineCashPaid: o.onlineCashPaid,
    onlineCardPaid: o.onlineCardPaid,
    onlinePaidOnline: o.onlinePaidOnline,
    onlinePending: o.onlinePending,
    onlinePaidTotal: o.onlinePaidTotal,
    onlineRevenueInfo: o.kpiOnlineRevenueInfo,
    topProducts: r.topProductsTitle,
    colRank: r.colRank,
    colProduct: r.colProduct,
    colQuantity: r.colQuantity,
    colShare: r.colShare,
    colCategory: r.colCategory,
    topEmployees: r.topEmployeesTitle,
    colEmployee: r.colEmployee,
    colAvgOrder: r.colAvgOrder,
    topEmployeesEmpty: r.topEmployeesEmpty,
    taxes: r.taxesTitle,
    taxesScopeNote: r.taxesPosOnlyNote,
    taxNetRevenue: r.taxNetRevenue,
    taxVat: r.taxVat,
    taxGrossRevenue: r.taxGrossRevenue,
    taxFiscalReceipts: r.taxFiscalReceipts,
    businessTrends: r.trendsTitle,
    trendBestDay: r.trendBestDay,
    trendBestMonth: r.trendBestMonth,
    trendBestHour: r.trendBestHour,
    trendLargestReceipt: r.trendLargestReceipt,
    trendTopPayment: r.trendTopPayment,
    trendTopProduct: r.trendTopProduct,
    salesByHour: r.hourlySalesTitle,
    revenueSection: r.revenueChartTitle,
    dash,
  };
}

export function buildOrdersDocumentLabels(
  t: PortalTranslations,
): OrdersDocumentLabels {
  const pdf = t.pdfDocuments;
  const o = t.orders;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.ordersTitle,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    executiveSummary: pdf.executiveSummary,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    totals: pdf.totals,
    hour: pdf.hour,
    colRevenue: o.colAmount,
    colOrders: o.kpiOrders,
    segment: pdf.segment,
    noData: pdf.noData,
    ordersSummary: pdf.ordersSummary,
    revenueSummary: pdf.revenueSummary,
    posPaymentSummaryTitle: o.paymentSummaryTitle,
    onlinePaymentSummaryTitle: o.onlinePaymentSummaryTitle,
    onlineRevenueHint: o.kpiOnlineRevenueInfo,
    paymentTotal: pdf.paymentTotal,
    kpiAllOrders: o.kpiAllOrders,
    kpiPosOrders: o.kpiPosOrders,
    kpiOnlineOrders: o.kpiOnlineOrders,
    kpiOrders: o.kpiOrders,
    kpiReceipts: o.kpiReceipts,
    kpiRefunds: o.kpiRefunds,
    kpiOpenShift: o.kpiOpenShift,
    kpiPosRevenue: o.kpiPosRevenue,
    kpiOnlineRevenue: o.kpiOnlineRevenue,
    kpiTotalRevenue: o.kpiTotalRevenue,
    openShiftYes: o.openShiftYes,
    openShiftNo: o.openShiftNo,
    paymentCash: o.paymentCash,
    paymentCard: o.paymentCard,
    paymentVoucher: o.paymentVoucher,
    paymentOther: o.paymentOther,
    onlineCashPaid: o.onlineCashPaid,
    onlineCardPaid: o.onlineCardPaid,
    onlinePaidOnline: o.onlinePaidOnline,
    onlinePending: o.onlinePending,
    onlinePaidTotal: o.onlinePaidTotal,
    posOrdersTitle: o.ordersFeedTitle,
    onlineOrdersTitle: o.onlineOrdersTitle,
    onlineOrdersEmpty: o.onlineOrdersEmpty,
    unknownProvider: o.unknownProvider,
    allReceipts: pdf.allReceipts,
    colTime: o.colTime,
    colOrderNumber: o.colOrderNumber,
    colStatus: o.colStatus,
    colPayment: o.colPayment,
    colAmount: o.colAmount,
    colCashier: o.colCashier,
    colDevice: o.colDevice,
    colReceipt: o.colReceipt,
    colCustomer: o.colCustomer,
    colProvider: o.colProvider,
    colFiscal: o.colFiscal,
    ordersEmpty: o.ordersEmpty,
    receiptsEmpty: o.receiptsEmpty,
    dash: t.labels.dash,
    statusLabels: { ...o.statusLabels },
  };
}

export function buildOrderDetailDocumentLabels(
  t: PortalTranslations,
): OrderDetailDocumentLabels {
  const pdf = t.pdfDocuments;
  const o = t.orders;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.orderDetailTitle,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    orderNumber: o.colOrderNumber,
    status: o.colStatus,
    payment: o.colPayment,
    orderSource: o.orderSourceLabel,
    provider: o.colProvider,
    platform: o.colPlatform,
    receipt: o.colReceipt,
    cashier: o.colCashier,
    device: o.colDevice,
    businessDate: o.colBusinessDate,
    customer: o.colCustomer,
    phone: o.colPhone,
    sectionOverview: o.sectionOverview,
    sectionCustomer: o.sectionCustomer,
    sectionProducts: o.sectionProducts,
    sectionTotals: o.sectionTotals,
    sectionPayment: o.sectionPayment,
    sectionActivity: o.sectionActivity,
    productsEmpty: o.productsEmpty,
    activityEmpty: o.activityEmpty,
    discounts: o.colDiscounts,
    net: o.colNet,
    tax: o.colTax,
    gross: o.colGross,
    colProduct: o.colProduct,
    colQuantity: o.colQuantity,
    colUnitPrice: o.colUnitPrice,
    colLineTotal: o.colLineTotal,
    colAmount: o.colAmount,
    paymentCash: o.paymentCash,
    paymentCard: o.paymentCard,
    paymentVoucher: o.paymentVoucher,
    paymentOther: o.paymentOther,
    dash: t.labels.dash,
    sourceOrder: o.sourceOrder,
    sourceReceipt: o.sourceReceipt,
    statusLabels: { ...o.statusLabels },
  };
}

export function buildReceiptDocumentLabels(
  t: PortalTranslations,
): ReceiptDocumentLabels {
  const pdf = t.pdfDocuments;
  const o = t.orders;
  const dash = t.labels.dash;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.receiptTitle,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    executiveSummary: pdf.executiveSummary,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    totals: pdf.totals,
    hour: pdf.hour,
    colRevenue: o.colAmount,
    colOrders: o.kpiOrders,
    segment: pdf.segment,
    noData: pdf.noData,
    receiptDetails: o.receiptDetailTitle,
    fiscalPendingNote: o.receiptFiscalPending,
    itemsTitle: o.receiptItemsTitle,
    itemsEmpty: o.receiptItemsEmpty,
    colProduct: o.colProduct,
    colQuantity: o.colQuantity,
    colUnitPrice: o.colUnitPrice,
    colLineTotal: o.colLineTotal,
    colReceipt: o.colReceipt,
    colTime: o.colTime,
    colCustomer: o.colCustomer,
    colPayment: o.colPayment,
    colFiscal: o.colFiscal,
    colAmount: o.colAmount,
    colDevice: o.colDevice,
    paymentCash: o.paymentCash,
    paymentCard: o.paymentCard,
    paymentVoucher: o.paymentVoucher,
    paymentOther: o.paymentOther,
    dash,
  };
}

export function buildReceiptDetailDocumentLabels(
  t: PortalTranslations,
): ReceiptDetailDocumentLabels {
  const pdf = t.pdfDocuments;
  const r = t.receipts;
  const o = t.orders;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.receiptTitle,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    receiptDetails: r.detailTitle,
    colReceipt: r.colReceiptNumber,
    colTime: r.colTime,
    colCustomer: o.colCustomer,
    colPayment: r.colPayment,
    colFiscal: r.colFiscal,
    colAmount: r.colAmount,
    colDevice: r.colDevice,
    colCashier: r.colCashier,
    colStatus: r.colStatus,
    colProduct: r.colProduct,
    colQuantity: r.colQuantity,
    colUnitPrice: r.colUnitPrice,
    colLineTotal: r.colLineTotal,
    itemsTitle: r.itemsTitle,
    itemsEmpty: r.itemsEmpty,
    totalsTitle: r.totalsTitle,
    discounts: o.colDiscounts,
    netTotal: r.netTotal,
    taxTotal: r.taxTotal,
    grossTotal: r.grossTotal,
    sectionPayment: r.sectionPayment,
    sectionFiscal: r.sectionFiscal,
    sectionPrintStats: r.printStatsTitle,
    sectionActivity: r.sectionActivity,
    fiscalPendingNote: r.fiscalPending,
    originalPrint: r.originalPrint,
    reprintCount: r.reprintCountLabel,
    lastPrintTime: r.lastPrintTime,
    activityEmpty: r.historyEmpty,
    paymentCash: r.paymentCash,
    paymentCard: r.paymentCard,
    paymentVoucher: r.paymentVoucher,
    paymentOther: r.paymentOther,
    yes: r.printYes,
    no: r.printNo,
    dash: t.labels.dash,
    statusActive: r.statusActive,
    statusRefunded: r.statusRefunded,
    statusPartialRefund: r.statusPartialRefund,
    statusVoided: r.statusVoided,
  };
}

export function buildReceiptsListDocumentLabels(
  t: PortalTranslations,
): ReceiptsListDocumentLabels {
  const pdf = t.pdfDocuments;
  const r = t.receipts;

  return {
    brandCloud: pdf.brandCloud,
    docTitle: pdf.receiptsReportTitle,
    generatedBy: pdf.generatedBy,
    website: pdf.website,
    business: pdf.business,
    store: pdf.store,
    period: pdf.period,
    date: pdf.date,
    generatedAt: pdf.generatedAt,
    timezone: pdf.timezone,
    currency: pdf.currency,
    receiptSummary: pdf.receiptSummary,
    paymentSummary: r.paymentSummaryTitle,
    paymentTotal: pdf.paymentTotal,
    kpiPosRevenue: r.kpiPosRevenue,
    kpiReceipts: r.kpiReceiptsPeriod,
    kpiActiveReceipts: r.kpiActiveReceipts,
    kpiPrinted: r.kpiPrinted,
    kpiReprinted: r.kpiReprinted,
    kpiRefunds: r.kpiRefunds,
    paymentCash: r.paymentCash,
    paymentCard: r.paymentCard,
    paymentVoucher: r.paymentVoucher,
    paymentOther: r.paymentOther,
    tableTitle: r.tableTitle,
    tableEmpty: r.tableEmpty,
    colReceiptNumber: r.colReceiptNumber,
    colDate: r.colDate,
    colTime: r.colTime,
    colCashier: r.colCashier,
    colPayment: r.colPayment,
    colAmount: r.colAmount,
    colStatus: r.colStatus,
    colFiscal: r.colFiscal,
    colPrintCount: r.colPrintCount,
    colLastEvent: r.colLastEvent,
    statusActive: r.statusActive,
    statusRefunded: r.statusRefunded,
    statusPartialRefund: r.statusPartialRefund,
    statusVoided: r.statusVoided,
    dash: t.labels.dash,
  };
}
