import type { CountryConfigEntry } from "../types.js";

/** Mirrors drizzle/019_country_config.sql seed — used in unit tests without DB. */
export const SEED_COUNTRY_CONFIG: CountryConfigEntry[] = [
  {
    code: "DE",
    nameDe: "Deutschland",
    nameEn: "Germany",
    currency: "EUR",
    allowedCurrencies: ["EUR"],
    fiscalRequired: true,
    fiscalProvider: "fiskaly",
    receiptMode: "certified",
    fiscalSurchargeCents: 500,
    posDownloadAllowed: true,
    status: "active",
    sortOrder: 1,
  },
  {
    code: "AT",
    nameDe: "Österreich",
    nameEn: "Austria",
    currency: "EUR",
    allowedCurrencies: ["EUR"],
    fiscalRequired: true,
    fiscalProvider: null,
    receiptMode: "standard_until_certified",
    fiscalSurchargeCents: 0,
    posDownloadAllowed: true,
    status: "coming_soon",
    sortOrder: 2,
  },
  {
    code: "TN",
    nameDe: "Tunesien",
    nameEn: "Tunisia",
    currency: "TND",
    allowedCurrencies: ["TND"],
    fiscalRequired: false,
    fiscalProvider: null,
    receiptMode: "standard",
    fiscalSurchargeCents: 0,
    posDownloadAllowed: true,
    status: "active",
    sortOrder: 12,
  },
  {
    code: "MA",
    nameDe: "Marokko",
    nameEn: "Morocco",
    currency: "MAD",
    allowedCurrencies: ["MAD"],
    fiscalRequired: false,
    fiscalProvider: null,
    receiptMode: "standard",
    fiscalSurchargeCents: 0,
    posDownloadAllowed: true,
    status: "active",
    sortOrder: 13,
  },
  {
    code: "DZ",
    nameDe: "Algerien",
    nameEn: "Algeria",
    currency: "DZD",
    allowedCurrencies: ["DZD"],
    fiscalRequired: false,
    fiscalProvider: null,
    receiptMode: "standard",
    fiscalSurchargeCents: 0,
    posDownloadAllowed: true,
    status: "active",
    sortOrder: 14,
  },
  {
    code: "LY",
    nameDe: "Libyen",
    nameEn: "Libya",
    currency: "LYD",
    allowedCurrencies: ["LYD"],
    fiscalRequired: false,
    fiscalProvider: null,
    receiptMode: "standard",
    fiscalSurchargeCents: 0,
    posDownloadAllowed: true,
    status: "active",
    sortOrder: 15,
  },
  {
    code: "OTHER",
    nameDe: "Sonstiges",
    nameEn: "Other",
    currency: "EUR",
    allowedCurrencies: ["EUR"],
    fiscalRequired: false,
    fiscalProvider: null,
    receiptMode: "standard",
    fiscalSurchargeCents: 0,
    posDownloadAllowed: true,
    status: "active",
    sortOrder: 17,
  },
];
